params:
  samples: "samples.tsv"

  import:
    type: "SampleData[PairedEndSequencesWithQuality]"
    format: "PairedEndFastqManifestPhred64V2"
    #format: CasavaOneEightSingleLanePerSampleDirFmt

  denoise:
    threads: 8
    dada2:
      do: True
      trunc_len_f: 280
      trunc_len_r: 250
      trim_left_f: 0
      trim_left_r: 0
    deblur:
      do: False
      trim_len: 280
      left_trim_len: 0
  taxonomic:
    threads: 8
    classifier: /home/zhujie/databases/ecogenomics/QIIME2/taxonomic_classifier/silva-138-99-nb-classifier.qza

output:
  import: "results/00.import"
  denoise: "results/01.denoise"
  taxonomic: "results/03.taxonomic"

envs:
  qiime2: "envs/qiime2.yaml"
