params:
  samples: "samples.tsv"
  type: "SampleData[PairedEndSequencesWithQuality]"
  format: "PairedEndFastqManifestPhred64V2"

output:
  import: "results/00.import"

envs:
  qiime2: "envs/qiime2.yaml"
